import { Category, FAQItem, Product, Testimonial } from "./types";

export const SITE = {
  name: "FlixMart",
  tagline: "Premium Digital Subscriptions & AI Tools",
  whatsapp: "923044603133",
  email: "support@flixmart.online",
  currency: "PKR",
  domain: "https://flixmart.online",
  paymentAccount: "03044603133"
};

export const categories: Category[] = [
  { slug: "iptv", name: "IPTV", description: "Live TV, sports, movies and international entertainment in one place.", icon: "Tv" },
  { slug: "ai-tools", name: "AI Tools", description: "Premium AI assistants, research, writing and productivity tools.", icon: "Bot" },
  { slug: "graphics-video-tools", name: "Graphics/Video Tools", description: "Professional design, graphics, video and creator software.", icon: "Palette" },
  { slug: "ai-videos", name: "AI Videos", description: "Next-generation AI video creation, editing and generation platforms.", icon: "Video" },
  { slug: "entertainment", name: "Entertainment", description: "Premium streaming, music and entertainment subscriptions.", icon: "Film" },
  { slug: "academic-writing-tools", name: "Academic/Writing Tools", description: "Writing, research, study and academic productivity tools.", icon: "BookOpen" },
  { slug: "business-tools", name: "Business Tools", description: "Business, collaboration, presentations and professional productivity tools.", icon: "Briefcase" },
  { slug: "vpn", name: "VPN", description: "Privacy and security tools for safer browsing and digital access.", icon: "ShieldCheck" }
];

/* FlixMart starter catalog: IPTV plus the clearly readable products from the supplied KingMotions screenshots. */
export const products: Product[] = [
{
    slug: "iptv-starter",
    name: "IPTV Starter",
    category: "iptv",
    tagline: "Affordable streaming package for casual viewers",
    description:
      "IPTV Starter provides a reliable channel package for everyday TV, news, and entertainment. Test our service risk-free with a 24-hour free trial.",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80",
    brandKey: "iptv-starter",
    rating: 4.6,
    reviews: 210,
    deliveryTime: "Within 30 minutes",
    plans: [
      { label: "24 Hours", price: 0, duration: "24 hours", isFree: true, badge: "FREE TRIAL" },
      { label: "1 Month", price: 790, originalPrice: 2250, duration: "30 days" },
      { label: "3 Months", price: 1960, originalPrice: 5600, duration: "90 days" },
      { label: "6 Months", price: 3430, originalPrice: 9800, duration: "180 days" },
      { label: "1 Year", price: 5390, originalPrice: 15400, duration: "365 days" }
    ],
    features: [
      "Curated live TV channels",
      "Movies & series library",
      "HD / FHD streaming quality",
      "EPG guide integration",
      "Smart TV, Firestick & Android support"
    ],
    included: ["M3U playlist link or portal URL", "Step-by-step setup guide for your device"],
    faqs: [
      { question: "How do I claim the 24-hour free trial?", answer: "Click 'Claim Free Trial on WhatsApp' to request trial credentials from our team instantly." }
    ],
    isIPTV: true,
    iptvTier: "Starter",
    quality: "HD / FHD",
    contentRegions: ["UK", "USA", "Canada", "Europe", "International"],
    epgSupported: true,
    devicesSupported: ["Smart TV", "Firestick", "Android Box", "iOS", "Windows / Mac"],
    channelCountText: "Essential Live Channels",
    movieCountText: "Popular Movie Catalog",
    seriesCountText: "Standard Series Library"
  },
{
    slug: "iptv-standard",
    name: "IPTV Standard",
    category: "iptv",
    tagline: "Balanced IPTV package for families & daily entertainment",
    description:
      "IPTV Standard offers broader live TV channel options, sports coverage, and expanded movie libraries. Includes a 24-hour free trial.",
    image: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80",
    brandKey: "iptv-standard",
    rating: 4.7,
    reviews: 380,
    deliveryTime: "Within 30 minutes",
    plans: [
      { label: "24 Hours", price: 0, duration: "24 hours", isFree: true, badge: "FREE TRIAL" },
      { label: "1 Month", price: 980, originalPrice: 2800, duration: "30 days" },
      { label: "3 Months", price: 2450, originalPrice: 7000, duration: "90 days" },
      { label: "6 Months", price: 4410, originalPrice: 12600, duration: "180 days" },
      { label: "1 Year", price: 6860, originalPrice: 19600, duration: "365 days" }
    ],
    features: [
      "Expanded live TV selection",
      "Full VOD movie & series updates",
      "FHD / 4K stream options",
      "EPG guide support",
      "Multi-device compatibility"
    ],
    included: ["Playlist credentials", "Device setup instructions", "Support assistance"],
    faqs: [
      { question: "Does Standard include sports channels?", answer: "Yes, major sports streams in HD/FHD are available." }
    ],
    isIPTV: true,
    iptvTier: "Standard",
    quality: "FHD / 4K",
    contentRegions: ["UK", "USA", "Canada", "Europe", "Middle East", "International"],
    epgSupported: true,
    devicesSupported: ["Smart TV", "Firestick", "Android Box", "Apple TV", "MAG Box"],
    channelCountText: "Broad Live Channels",
    movieCountText: "Expanded VOD Movies",
    seriesCountText: "Updated TV Series"
  },
{
    slug: "iptv-premium",
    name: "IPTV Premium",
    category: "iptv",
    tagline: "Comprehensive entertainment & live sports package",
    description:
      "Our most popular IPTV tier — extensive live channels, sports coverage, 4K streams, and fast server stability worldwide. Try it free for 24 hours.",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80",
    brandKey: "iptv-premium",
    badge: "Most Popular",
    rating: 4.9,
    reviews: 840,
    deliveryTime: "Within 15 minutes",
    plans: [
      { label: "24 Hours", price: 0, duration: "24 hours", isFree: true, badge: "FREE TRIAL" },
      { label: "1 Month", price: 1280, originalPrice: 3650, duration: "30 days" },
      { label: "3 Months", price: 3240, originalPrice: 9250, duration: "90 days" },
      { label: "6 Months", price: 5880, originalPrice: 16800, duration: "180 days" },
      { label: "1 Year", price: 8820, originalPrice: 25200, duration: "365 days" }
    ],
    features: [
      "Extensive global live TV channels",
      "Huge movie & series VOD archive",
      "Live sports coverage in FHD/4K",
      "Interactive EPG program guide",
      "Fast response anti-buffer servers",
      "Free 24-hour trial available"
    ],
    included: ["Playlist credentials & portal URL", "Dedicated setup assistance", "Warranty uptime guarantee"],
    faqs: [
      { question: "Why is IPTV Premium the most popular choice?", answer: "It delivers the best balance of server speed, channel variety, sports streams, and 4K VOD content." }
    ],
    isIPTV: true,
    iptvTier: "Premium",
    quality: "FHD / 4K Ultra",
    contentRegions: ["UK", "USA", "Canada", "Europe", "Middle East", "South Asia", "International"],
    epgSupported: true,
    devicesSupported: ["Smart TV", "Firestick", "TiviMate", "Android / iOS", "Formuler / MAG"],
    channelCountText: "Extensive Live Channels",
    movieCountText: "Comprehensive VOD Library",
    seriesCountText: "Complete Series Boxsets"
  },
{
    slug: "iptv-ultimate",
    name: "IPTV Ultimate",
    category: "iptv",
    tagline: "Top-tier package for broad content selection & priority support",
    description:
      "IPTV Ultimate is designed for power viewers who demand maximum channel variety, complete international content coverage, and priority technical support.",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&q=80",
    brandKey: "iptv-ultimate",
    badge: "Trending",
    rating: 4.9,
    reviews: 490,
    deliveryTime: "Within 15 minutes",
    plans: [
      { label: "24 Hours", price: 0, duration: "24 hours", isFree: true, badge: "FREE TRIAL" },
      { label: "1 Month", price: 1580, originalPrice: 4500, duration: "30 days" },
      { label: "3 Months", price: 3920, originalPrice: 11200, duration: "90 days" },
      { label: "6 Months", price: 7350, originalPrice: 21000, duration: "180 days" },
      { label: "1 Year", price: 10780, originalPrice: 30800, duration: "365 days" }
    ],
    features: [
      "Broad global channel selection",
      "Full movies & TV series library",
      "Live sports & PPV events coverage",
      "Full EPG TV guide",
      "Multi-server backup lines",
      "Priority customer assistance"
    ],
    included: ["VIP M3U & portal link", "Priority setup & troubleshooting"],
    faqs: [
      { question: "Is technical help available for setup?", answer: "Yes, Ultimate users get priority assistance on WhatsApp." }
    ],
    isIPTV: true,
    iptvTier: "Ultimate",
    quality: "FHD / 4K / UHD",
    contentRegions: ["UK", "USA", "Canada", "Europe", "Middle East", "South Asia", "India", "Pakistan", "International"],
    epgSupported: true,
    devicesSupported: ["Smart TV", "Firestick", "TiviMate", "Formuler", "MAG", "Android / iOS"],
    channelCountText: "Maximum Live Channels",
    movieCountText: "Complete VOD Vault",
    seriesCountText: "Full Boxsets & Seasons"
  },
  {
    slug: "fish-audio",
    name: "Fish Audio",
    category: "ai-tools",
    tagline: "Premium Fish Audio access for work, study, creativity and everyday use.",
    description: "Get convenient access to Fish Audio with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "fish-audio",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 9000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "chatgpt",
    name: "ChatGPT",
    category: "ai-tools",
    tagline: "Premium ChatGPT access for work, study, creativity and everyday use.",
    description: "Get convenient access to ChatGPT with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "chatgpt",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 900, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "grok",
    name: "Grok",
    category: "ai-tools",
    tagline: "Premium Grok access for work, study, creativity and everyday use.",
    description: "Get convenient access to Grok with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "grok",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "cursor-ai",
    name: "Cursor AI",
    category: "ai-tools",
    tagline: "Premium Cursor AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Cursor AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "cursor-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "rezi-ai",
    name: "Rezi AI",
    category: "ai-tools",
    tagline: "Premium Rezi AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Rezi AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "rezi-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    category: "ai-tools",
    tagline: "Premium ElevenLabs access for work, study, creativity and everyday use.",
    description: "Get convenient access to ElevenLabs with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "elevenlabs",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2600, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "claude-ai",
    name: "Claude AI",
    category: "ai-tools",
    tagline: "Premium Claude AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Claude AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "claude-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 5300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "gamma-ai",
    name: "Gamma AI",
    category: "ai-tools",
    tagline: "Premium Gamma AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Gamma AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "gamma-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "notegpt",
    name: "NoteGPT",
    category: "ai-tools",
    tagline: "Premium NoteGPT access for work, study, creativity and everyday use.",
    description: "Get convenient access to NoteGPT with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "notegpt",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "genspark-ai",
    name: "Genspark AI",
    category: "ai-tools",
    tagline: "Premium Genspark AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Genspark AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "genspark-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 6000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "base44",
    name: "Base44",
    category: "ai-tools",
    tagline: "Premium Base44 access for work, study, creativity and everyday use.",
    description: "Get convenient access to Base44 with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "base44",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "lovable-dev",
    name: "Lovable.dev",
    category: "ai-tools",
    tagline: "Premium Lovable.dev access for work, study, creativity and everyday use.",
    description: "Get convenient access to Lovable.dev with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "lovable-dev",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 5000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "kittl",
    name: "Kittl",
    category: "graphics-video-tools",
    tagline: "Premium Kittl access for work, study, creativity and everyday use.",
    description: "Get convenient access to Kittl with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "kittl",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "autodesk",
    name: "Autodesk",
    category: "graphics-video-tools",
    tagline: "Premium Autodesk access for work, study, creativity and everyday use.",
    description: "Get convenient access to Autodesk with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "autodesk",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 7500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "blender",
    name: "Blender",
    category: "graphics-video-tools",
    tagline: "Premium Blender access for work, study, creativity and everyday use.",
    description: "Get convenient access to Blender with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "blender",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 5000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "submagic",
    name: "Submagic",
    category: "graphics-video-tools",
    tagline: "Premium Submagic access for work, study, creativity and everyday use.",
    description: "Get convenient access to Submagic with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "submagic",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "freepik-magnific",
    name: "Freepik/Magnific",
    category: "graphics-video-tools",
    tagline: "Premium Freepik/Magnific access for work, study, creativity and everyday use.",
    description: "Get convenient access to Freepik/Magnific with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "freepik-magnific",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "envato-elements",
    name: "Envato Elements",
    category: "graphics-video-tools",
    tagline: "Premium Envato Elements access for work, study, creativity and everyday use.",
    description: "Get convenient access to Envato Elements with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "envato-elements",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "storyblocks",
    name: "Storyblocks",
    category: "graphics-video-tools",
    tagline: "Premium Storyblocks access for work, study, creativity and everyday use.",
    description: "Get convenient access to Storyblocks with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "storyblocks",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 1200, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "canva",
    name: "Canva",
    category: "graphics-video-tools",
    tagline: "Premium Canva access for work, study, creativity and everyday use.",
    description: "Get convenient access to Canva with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "canva",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "capcut-pro",
    name: "CapCut Pro",
    category: "graphics-video-tools",
    tagline: "Premium CapCut Pro access for work, study, creativity and everyday use.",
    description: "Get convenient access to CapCut Pro with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "capcut-pro",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 750, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "adobe-creative-cloud",
    name: "Adobe Creative Cloud",
    category: "graphics-video-tools",
    tagline: "Premium Adobe Creative Cloud access for work, study, creativity and everyday use.",
    description: "Get convenient access to Adobe Creative Cloud with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "adobe-creative-cloud",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 1500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "vectorizer-ai",
    name: "Vectorizer AI",
    category: "graphics-video-tools",
    tagline: "Premium Vectorizer AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Vectorizer AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "vectorizer-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 1500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "figma",
    name: "Figma",
    category: "graphics-video-tools",
    tagline: "Premium Figma access for work, study, creativity and everyday use.",
    description: "Get convenient access to Figma with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "figma",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "google-ai-ultra-veo3-flow",
    name: "Google AI Ultra VEO3 | Flow",
    category: "ai-videos",
    tagline: "Premium Google AI Ultra VEO3 | Flow access for work, study, creativity and everyday use.",
    description: "Get convenient access to Google AI Ultra VEO3 | Flow with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "google-ai-ultra-veo3-flow",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "magiclight-ai",
    name: "MagicLight AI",
    category: "ai-videos",
    tagline: "Premium MagicLight AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to MagicLight AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "magiclight-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "akool",
    name: "Akool",
    category: "ai-videos",
    tagline: "Premium Akool access for work, study, creativity and everyday use.",
    description: "Get convenient access to Akool with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "akool",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "d-id",
    name: "D-ID",
    category: "ai-videos",
    tagline: "Premium D-ID access for work, study, creativity and everyday use.",
    description: "Get convenient access to D-ID with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "d-id",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "vyond",
    name: "Vyond",
    category: "ai-videos",
    tagline: "Premium Vyond access for work, study, creativity and everyday use.",
    description: "Get convenient access to Vyond with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "vyond",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 14000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "animaker",
    name: "Animaker",
    category: "ai-videos",
    tagline: "Premium Animaker access for work, study, creativity and everyday use.",
    description: "Get convenient access to Animaker with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "animaker",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "runway",
    name: "Runway",
    category: "ai-videos",
    tagline: "Premium Runway access for work, study, creativity and everyday use.",
    description: "Get convenient access to Runway with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "runway",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 21500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "heygen",
    name: "HeyGen",
    category: "ai-videos",
    tagline: "Premium HeyGen access for work, study, creativity and everyday use.",
    description: "Get convenient access to HeyGen with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "heygen",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 6500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "viewmax",
    name: "ViewMax",
    category: "ai-videos",
    tagline: "Premium ViewMax access for work, study, creativity and everyday use.",
    description: "Get convenient access to ViewMax with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "viewmax",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "pictory-ai",
    name: "Pictory AI",
    category: "ai-videos",
    tagline: "Premium Pictory AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Pictory AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "pictory-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 5000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "kling-ai",
    name: "Kling AI",
    category: "ai-videos",
    tagline: "Premium Kling AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Kling AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "kling-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 6000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo AI",
    category: "ai-videos",
    tagline: "Premium Leonardo AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Leonardo AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "leonardo-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "iqiyi",
    name: "iQIYI",
    category: "entertainment",
    tagline: "Premium iQIYI access for work, study, creativity and everyday use.",
    description: "Get convenient access to iQIYI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "iqiyi",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 1000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "netflix",
    name: "Netflix",
    category: "entertainment",
    tagline: "Premium Netflix access for work, study, creativity and everyday use.",
    description: "Get convenient access to Netflix with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "netflix",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "prime-video",
    name: "Prime Video",
    category: "entertainment",
    tagline: "Premium Prime Video access for work, study, creativity and everyday use.",
    description: "Get convenient access to Prime Video with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "prime-video",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "apple-tv",
    name: "Apple TV",
    category: "entertainment",
    tagline: "Premium Apple TV access for work, study, creativity and everyday use.",
    description: "Get convenient access to Apple TV with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "apple-tv",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "paramount-plus",
    name: "Paramount Plus",
    category: "entertainment",
    tagline: "Premium Paramount Plus access for work, study, creativity and everyday use.",
    description: "Get convenient access to Paramount Plus with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "paramount-plus",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 400, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "starzplay",
    name: "Starzplay",
    category: "entertainment",
    tagline: "Premium Starzplay access for work, study, creativity and everyday use.",
    description: "Get convenient access to Starzplay with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "starzplay",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "youtube-premium",
    name: "YouTube Premium",
    category: "entertainment",
    tagline: "Premium YouTube Premium access for work, study, creativity and everyday use.",
    description: "Get convenient access to YouTube Premium with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "youtube-premium",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "zee5",
    name: "Zee5",
    category: "entertainment",
    tagline: "Premium Zee5 access for work, study, creativity and everyday use.",
    description: "Get convenient access to Zee5 with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "zee5",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 400, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "spotify",
    name: "Spotify",
    category: "entertainment",
    tagline: "Premium Spotify access for work, study, creativity and everyday use.",
    description: "Get convenient access to Spotify with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "spotify",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 350, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "peacock-tv",
    name: "Peacock TV",
    category: "entertainment",
    tagline: "Premium Peacock TV access for work, study, creativity and everyday use.",
    description: "Get convenient access to Peacock TV with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "peacock-tv",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "tapmad",
    name: "Tapmad",
    category: "entertainment",
    tagline: "Premium Tapmad access for work, study, creativity and everyday use.",
    description: "Get convenient access to Tapmad with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "tapmad",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 350, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "crunchyroll",
    name: "Crunchyroll",
    category: "entertainment",
    tagline: "Premium Crunchyroll access for work, study, creativity and everyday use.",
    description: "Get convenient access to Crunchyroll with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "crunchyroll",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "quetext",
    name: "Quetext",
    category: "academic-writing-tools",
    tagline: "Premium Quetext access for work, study, creativity and everyday use.",
    description: "Get convenient access to Quetext with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "quetext",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "overleaf",
    name: "Overleaf",
    category: "academic-writing-tools",
    tagline: "Premium Overleaf access for work, study, creativity and everyday use.",
    description: "Get convenient access to Overleaf with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "overleaf",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    category: "academic-writing-tools",
    tagline: "Premium Grammarly access for work, study, creativity and everyday use.",
    description: "Get convenient access to Grammarly with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "grammarly",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "quillbot",
    name: "QuillBot",
    category: "academic-writing-tools",
    tagline: "Premium QuillBot access for work, study, creativity and everyday use.",
    description: "Get convenient access to QuillBot with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "quillbot",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "perplexity-ai",
    name: "Perplexity AI",
    category: "academic-writing-tools",
    tagline: "Premium Perplexity AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Perplexity AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "perplexity-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "scite-ai",
    name: "Scite AI",
    category: "academic-writing-tools",
    tagline: "Premium Scite AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Scite AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "scite-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "paperpal",
    name: "Paperpal",
    category: "academic-writing-tools",
    tagline: "Premium Paperpal access for work, study, creativity and everyday use.",
    description: "Get convenient access to Paperpal with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "paperpal",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 800, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "quizlet",
    name: "Quizlet",
    category: "academic-writing-tools",
    tagline: "Premium Quizlet access for work, study, creativity and everyday use.",
    description: "Get convenient access to Quizlet with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "quizlet",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    category: "academic-writing-tools",
    tagline: "Premium Writesonic access for work, study, creativity and everyday use.",
    description: "Get convenient access to Writesonic with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "writesonic",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 15000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "slideshare",
    name: "Slideshare",
    category: "academic-writing-tools",
    tagline: "Premium Slideshare access for work, study, creativity and everyday use.",
    description: "Get convenient access to Slideshare with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "slideshare",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "jenni-ai",
    name: "Jenni AI",
    category: "academic-writing-tools",
    tagline: "Premium Jenni AI access for work, study, creativity and everyday use.",
    description: "Get convenient access to Jenni AI with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "jenni-ai",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "wordtune",
    name: "Wordtune",
    category: "academic-writing-tools",
    tagline: "Premium Wordtune access for work, study, creativity and everyday use.",
    description: "Get convenient access to Wordtune with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "wordtune",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "prezi",
    name: "Prezi",
    category: "business-tools",
    tagline: "Premium Prezi access for work, study, creativity and everyday use.",
    description: "Get convenient access to Prezi with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "prezi",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 1500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "linkedin-premium-business-plan",
    name: "LinkedIn Premium Business Plan",
    category: "business-tools",
    tagline: "Premium LinkedIn Premium Business Plan access for work, study, creativity and everyday use.",
    description: "Get convenient access to LinkedIn Premium Business Plan with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "linkedin-premium-business-plan",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "linkedin-premium-career-plan",
    name: "LinkedIn Premium Career Plan",
    category: "business-tools",
    tagline: "Premium LinkedIn Premium Career Plan access for work, study, creativity and everyday use.",
    description: "Get convenient access to LinkedIn Premium Career Plan with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "linkedin-premium-career-plan",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "linkedin-premium-sales-navigator",
    name: "LinkedIn Premium Sales Navigator",
    category: "business-tools",
    tagline: "Premium LinkedIn Premium Sales Navigator access for work, study, creativity and everyday use.",
    description: "Get convenient access to LinkedIn Premium Sales Navigator with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "linkedin-premium-sales-navigator",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 4500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "novoresume",
    name: "NovoResume",
    category: "business-tools",
    tagline: "Premium NovoResume access for work, study, creativity and everyday use.",
    description: "Get convenient access to NovoResume with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "novoresume",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3300, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "tradingview",
    name: "TradingView",
    category: "business-tools",
    tagline: "Premium TradingView access for work, study, creativity and everyday use.",
    description: "Get convenient access to TradingView with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "tradingview",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 1900, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "loom",
    name: "Loom",
    category: "business-tools",
    tagline: "Premium Loom access for work, study, creativity and everyday use.",
    description: "Get convenient access to Loom with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "loom",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 3000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "miro-com",
    name: "Miro.com",
    category: "business-tools",
    tagline: "Premium Miro.com access for work, study, creativity and everyday use.",
    description: "Get convenient access to Miro.com with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "miro-com",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 2000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "dripify",
    name: "Dripify",
    category: "business-tools",
    tagline: "Premium Dripify access for work, study, creativity and everyday use.",
    description: "Get convenient access to Dripify with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "dripify",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 10000, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "nordvpn",
    name: "NordVPN",
    category: "vpn",
    tagline: "Premium NordVPN access for work, study, creativity and everyday use.",
    description: "Get convenient access to NordVPN with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "nordvpn",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 400, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "surfshark-vpn",
    name: "Surfshark VPN",
    category: "vpn",
    tagline: "Premium Surfshark VPN access for work, study, creativity and everyday use.",
    description: "Get convenient access to Surfshark VPN with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "surfshark-vpn",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 450, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "express-vpn",
    name: "Express VPN",
    category: "vpn",
    tagline: "Premium Express VPN access for work, study, creativity and everyday use.",
    description: "Get convenient access to Express VPN with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "express-vpn",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "proton-vpn",
    name: "Proton VPN",
    category: "vpn",
    tagline: "Premium Proton VPN access for work, study, creativity and everyday use.",
    description: "Get convenient access to Proton VPN with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "proton-vpn",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "pia-vpn",
    name: "PIA VPN",
    category: "vpn",
    tagline: "Premium PIA VPN access for work, study, creativity and everyday use.",
    description: "Get convenient access to PIA VPN with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "pia-vpn",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 500, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  },
  {
    slug: "hma-vpn",
    name: "HMA VPN",
    category: "vpn",
    tagline: "Premium HMA VPN access for work, study, creativity and everyday use.",
    description: "Get convenient access to HMA VPN with fast digital delivery and customer support.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    brandKey: "hma-vpn",
    rating: 4.8,
    reviews: 100,
    deliveryTime: "Within 30 minutes",
    plans: [{ label: "1 Month", price: 600, duration: "30 days" }],
    features: ["Digital access", "Fast delivery", "Customer support"],
    included: ["Activation/access details", "Setup assistance"],
    faqs: [{ question: "How quickly is delivery?", answer: "Orders are normally processed quickly after payment confirmation." }]
  }
];

export const testimonials: Testimonial[] = [
  {
    name: "Ahmed R.",
    location: "London, United Kingdom",
    rating: 5,
    quote: "Ordered ChatGPT Plus and had it activated in under 20 minutes. Support on WhatsApp was super responsive.",
    product: "ChatGPT Plus"
  },
  {
    name: "Fatima S.",
    location: "Dubai, UAE",
    rating: 5,
    quote: "Been using FlixMart for my Canva Pro and Netflix subscriptions for months now. Always reliable, always fast.",
    product: "Canva Pro"
  },
  {
    name: "James T.",
    location: "Toronto, Canada",
    rating: 5,
    quote: "Great prices, fast delivery, and helpful support. The activation process was simple and smooth. Highly recommend.",
    product: "Claude AI"
  },
  {
    name: "Sara M.",
    location: "Sydney, Australia",
    rating: 5,
    quote: "The IPTV Premium subscription has been rock solid, barely any buffering. Great channel selection.",
    product: "IPTV Premium"
  },
  {
    name: "Michael B.",
    location: "New York, USA",
    rating: 5,
    quote: "Fast delivery and an easy setup process. FlixMart support helped me get started without any hassle.",
    product: "Adobe Creative Cloud"
  },
  {
    name: "Layla H.",
    location: "Berlin, Germany",
    rating: 5,
    quote: "Customer support actually helps — walked me through setup on WhatsApp step by step. Will order again.",
    product: "Spotify Premium"
  }
];

export const homeFaqs: FAQItem[] = [
  {
    question: "How fast will I receive my subscription?",
    answer: "Most orders are delivered within 15 to 30 minutes of order confirmation. Specific delivery times are listed on each product page."
  },
  {
    question: "Are these genuine subscriptions?",
    answer: "Yes, all subscriptions are sourced through legitimate channels and backed by our replacement warranty."
  },
  {
    question: "How do I place an order?",
    answer: "Choose your product and plan, then click 'Buy Now' or 'Order on WhatsApp' to connect directly with our support team."
  },
  {
    question: "What payment methods are supported?",
    answer: "We support major credit/debit cards and international online payment options — our team confirms payment steps on WhatsApp."
  },
  {
    question: "Do you offer customer support after purchase?",
    answer: "Yes, our team is available on WhatsApp and email for activation assistance, troubleshooting, and support."
  },
  {
    question: "What if an account or activation has an issue?",
    answer: "Every order includes warranty coverage during which we provide a fast replacement or issue resolution."
  }
];
